{
    "name": "frontend",
    "version": "0.1.0",
    "private": true,
    "scripts": {
      "serve": "vue-cli-service serve",
      "build": "vue-cli-service build"
    },
    "dependencies": {
      "@ckeditor/ckeditor5-build-classic": "^24.0.0",
      "@ckeditor/ckeditor5-build-decoupled-document": "^24.0.0",
      "@ckeditor/ckeditor5-vue": "^2.0.1",
      "@ckeditor/ckeditor5-watchdog": "^24.0.0",
      "@fortawesome/fontawesome-free": "^5.15.1",
      "@livelybone/vue-datepicker": "^4.0.2",
      "@tinymce/tinymce-vue": "^4.0.0",
      "@types/chart.js": "^2.9.29",
      "@types/datatables.net": "^1.10.19",
      "@types/dropzone": "^5.7.3",
      "@types/jquery": "^3.5.4",
      "@types/lodash": "^4.14.166",
      "@types/select2": "^4.0.51",
      "@types/toastr": "^2.1.38",
      "axios": "^0.21.1",
      "bootstrap": "^4.5.3",
      "chart.js": "^2.9.4",
      "core-js": "^3.6.5",
      "cropperjs": "^1.5.9",
      "datatables.net": "^1.10.23",
      "datatables.net-bs4": "^1.10.19",
      "datatables.net-buttons": "^1.5.4",
      "datatables.net-buttons-bs4": "^1.5.4",
      "datatables.net-responsive-bs4": "^2.2.3",
      "datatables.net-select": "^1.2.7",
      "datatables.net-select-bs4": "^1.2.7",
      "dropzone": "^5.7.2",
      "fastest-validator": "^1.9.0",
      "jquery": "^3.5.1",
      "jszip": "^3.5.0",
      "lodash": "^4.17.20",
      "moment": "^2.22.2",
      "pdfmake": "^0.1.68",
      "perfect-scrollbar": "^1.5.0",
      "popper.js": "^1.16.1",
      "register-service-worker": "^1.7.1",
      "rxjs": "^6.6.3",
      "select2": "^4.0.13",
      "sweetalert2": "^10.12.6",
      "tinymce": "^5.6.2",
      "tinymce-vue": "^1.0.0",
      "toastr": "^2.1.4",
      "vue": "^3.0.0",
      "vue-class-component": "^8.0.0-0",
      "vue-flatpickr-component": "^9.0.3",
      "vue-loader-v16": "^16.0.0-beta.5.4",
      "vue-property-decorator": "^9.1.2",
      "vue-router": "^4.0.0-0",
      "vuex": "^4.0.0-0"
    },
    "devDependencies": {
      "@types/ckeditor__ckeditor5-core": "^11.0.3",
      "@vue/cli-plugin-babel": "~4.5.0",
      "@vue/cli-plugin-pwa": "~4.5.0",
      "@vue/cli-plugin-router": "~4.5.0",
      "@vue/cli-plugin-typescript": "~4.5.0",
      "@vue/cli-plugin-vuex": "~4.5.0",
      "@vue/cli-service": "~4.5.0",
      "@vue/compiler-sfc": "^3.0.0",
      "cross-env": "^7.0.3",
      "node-sass": "^4.12.0",
      "sass-loader": "^8.0.2",
      "typescript": "~3.9.3"
    }
  }